name: PR Cost Demo CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test stage 2
        run: |
          echo "Demo test stage"
          sleep 3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build stage
        run: |
          echo "Demo build stage"
          sleep 4